### ISSUE TITLE
Password Change Prompt

### ISSUE THREAD

**Issue by AmishaGeek** [geekwebsolution/password-protected-woo-store#30]
Password change does not prompt for re-entry.
After changing the password, if the user reverts to the original password, the system does not prompt for the password again. It should prompt every time a password is changed.

**Comment by kp2609** [comment]
I am closing this issue because this is an invalid  issue 

- if the user changes the password  and reverts it back again it will match with the cookie  saved in the user's PC that's why it does not display the password form
