### ISSUE TITLE
Subcategory Product Access

### ISSUE THREAD

**Issue by AmishaGeek** [geekwebsolution/password-protected-woo-store#33]
Subcategory products accessible despite parent category protection
 Protecting the parent category does not restrict access to subcategory products, which should also be protected.
https://prnt.sc/dYCFBzli9z9t
https://prnt.sc/mMld8ZLjXKd6

**Comment by kp2609** [comment]
i am closing this issue because it is an invalid question

we are not protecting sub category when the category I selected is protected. because it can create some conflict
If you want to protect sub-categories you need to select them as well
