### ISSUE TITLE
Encrypted password show in the password field in general settings page

### ISSUE THREAD

**Issue by aadityageek435** [geekwebsolution/password-protected-woo-store#36]
While testing with the database, I encountered an issue when the general password settings key was deleted from the options table. Upon refilling the settings in the password-protected plugin and saving them:
1. After setting the password and saving it for the first time, it displays the encrypted password as stored in the database (Screenshot: https://prnt.sc/CGxxZ6uKtleF).
2. This issue arises until we change the password it goes back to the unencrypted form (Screenshot: https://prnt.sc/BrIcXTQR1rUE).

**Comment by kp2609** [comment]
I'm closing this issue as it stems from an invalid question. 

Deleting the key from the database causes issues during submission because the password field is required. Without a value in the password field, the functionality cannot proceed, which leads to submission errors.
